package br.com.promon.horasxcoletoresstart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "HorasXColetoresStart", targetNamespace = "http://promon.com.br/HorasXColetoresStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface HorasXColetoresStart {

  /**
   * Java representation of web method [StartHorasXColetores].
   */
  @javax.jws.WebMethod(operationName = "StartHorasXColetores", action = "http://promon.com.br/EscalasStart/StartHorasXColetores")
  @javax.xml.ws.RequestWrapper(localName = "StartHorasXColetores", targetNamespace = "http://promon.com.br/HorasXColetoresStart/", className = "br.com.promon.horasxcoletoresstart.StartHorasXColetores")
  @javax.jws.Oneway
  public void startHorasXColetores(@javax.jws.WebParam(name = "data_inicio", targetNamespace = "") java.lang.String data_inicio, @javax.jws.WebParam(name = "data_fim", targetNamespace = "") java.lang.String data_fim);

}
