package br.com.promon.horasxcoletoresstart;

/**
 * Service implementation of {HorasXColetoresStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "HorasXColetoresStart", targetNamespace = "http://promon.com.br/HorasXColetoresStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/horasxcoletoresstart/HorasXColetoresStarter/HorasXColetoresStarter.wsdl")
public class HorasXColetoresStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL HORASXCOLETORESSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public HorasXColetoresStart_Service() throws java.net.MalformedURLException {
    super(HORASXCOLETORESSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/HorasXColetoresStart/", "HorasXColetoresStart"));
  }
  public HorasXColetoresStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [HorasXColetoresStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "HorasXColetoresStartSOAP")
  public br.com.promon.horasxcoletoresstart.HorasXColetoresStart getHorasXColetoresStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/HorasXColetoresStart/","HorasXColetoresStartSOAP");
    return (br.com.promon.horasxcoletoresstart.HorasXColetoresStart) super.getPort(portName,br.com.promon.horasxcoletoresstart.HorasXColetoresStart.class);
  }
}
