package br.com.promon.colaboradoresstart;

import java.util.Date;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "ColaboradoresStart", targetNamespace = "http://promon.com.br/ColaboradoresStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface ColaboradoresStart {

  /**
   * Java representation of web method [StartColaboradores].
   */
  @javax.jws.WebMethod(operationName = "StartColaboradores", action = "http://promon.com.br/ColaboradoresStart/StartColaboradores")
  @javax.xml.ws.RequestWrapper(localName = "StartColaboradores", targetNamespace = "http://promon.com.br/ColaboradoresStart/", className = "br.com.promon.colaboradoresstart.StartColaboradores")
  @javax.jws.Oneway
//  public void startColaboradores(@javax.jws.WebParam(name = "dat_refer", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar dat_refer, @javax.jws.WebParam(name = "log_ativos", targetNamespace = "") java.lang.Boolean log_ativos);
  public void startColaboradores(@javax.jws.WebParam(name = "dat_refer", targetNamespace = "") Date dat_refer, @javax.jws.WebParam(name = "log_ativos", targetNamespace = "") java.lang.Boolean log_ativos);

}
