package br.com.promon.colaboradoresstart;

/**
 * Service implementation of {ColaboradoresStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ColaboradoresStart", targetNamespace = "http://promon.com.br/ColaboradoresStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/colaboradoresstart/ColaboradoresStarter/ColaboradoresStarter.wsdl")
public class ColaboradoresStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL COLABORADORESSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public ColaboradoresStart_Service() throws java.net.MalformedURLException {
    super(COLABORADORESSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/ColaboradoresStart/", "ColaboradoresStart"));
  }
  public ColaboradoresStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ColaboradoresStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "ColaboradoresStartSOAP")
  public br.com.promon.colaboradoresstart.ColaboradoresStart getColaboradoresStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/ColaboradoresStart/","ColaboradoresStartSOAP");
    return (br.com.promon.colaboradoresstart.ColaboradoresStart) super.getPort(portName,br.com.promon.colaboradoresstart.ColaboradoresStart.class);
  }
}
