package br.com.promon.histsituacaostart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "HistSituacaoStart", targetNamespace = "http://promon.com.br/HistSituacaoStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface HistSituacaoStart {

  /**
   * Java representation of web method [StartHistSituacao].
   */
  @javax.jws.WebMethod(operationName = "StartHistSituacao", action = "http://promon.com.br/EscalasStart/StartHistSituacao")
  @javax.xml.ws.RequestWrapper(localName = "StartHistSituacao", targetNamespace = "http://promon.com.br/HistSituacaoStart/", className = "br.com.promon.histsituacaostart.StartHistSituacao")
  @javax.jws.Oneway
  public void startHistSituacao(@javax.jws.WebParam(name = "datRefer", targetNamespace = "") java.lang.String datRefer);

}
