package br.com.promon.histsituacaostart;

/**
 * Service implementation of {HistSituacaoStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "HistSituacaoStart", targetNamespace = "http://promon.com.br/HistSituacaoStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/histsituacaostart/HistSituacaoStartSOAP/HistSituacaoStartSOAP.wsdl")
public class HistSituacaoStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL HISTSITUACAOSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public HistSituacaoStart_Service() throws java.net.MalformedURLException {
    super(HISTSITUACAOSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/HistSituacaoStart/", "HistSituacaoStart"));
  }
  public HistSituacaoStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [HistSituacaoStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "HistSituacaoStartSOAP")
  public br.com.promon.histsituacaostart.HistSituacaoStart getHistSituacaoStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/HistSituacaoStart/","HistSituacaoStartSOAP");
    return (br.com.promon.histsituacaostart.HistSituacaoStart) super.getPort(portName,br.com.promon.histsituacaostart.HistSituacaoStart.class);
  }
}
