package br.com.promon.horasdiferenciadasstart;

/**
 * Service implementation of {HorasDiferenciadasStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "HorasDiferenciadasStart", targetNamespace = "http://promon.com.br/HorasDiferenciadasStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/horasdiferenciadasstart/HorasDiferenciadasStarter/HorasDiferenciadasStarter.wsdl")
public class HorasDiferenciadasStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL HORASDIFERENCIADASSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public HorasDiferenciadasStart_Service() throws java.net.MalformedURLException {
    super(HORASDIFERENCIADASSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/HorasDiferenciadasStart/", "HorasDiferenciadasStart"));
  }
  public HorasDiferenciadasStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [HorasDiferenciadasStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "HorasDiferenciadasStartSOAP")
  public br.com.promon.horasdiferenciadasstart.HorasDiferenciadasStart getHorasDiferenciadasStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/HorasDiferenciadasStart/","HorasDiferenciadasStartSOAP");
    return (br.com.promon.horasdiferenciadasstart.HorasDiferenciadasStart) super.getPort(portName,br.com.promon.horasdiferenciadasstart.HorasDiferenciadasStart.class);
  }
}
