package br.com.promon.horasdiferenciadasstart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "HorasDiferenciadasStart", targetNamespace = "http://promon.com.br/HorasDiferenciadasStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface HorasDiferenciadasStart {

  /**
   * Java representation of web method [StartHorasDiferenciadas].
   */
  @javax.jws.WebMethod(operationName = "StartHorasDiferenciadas", action = "http://promon.com.br/HorasDiferenciadasStart/StartHorasDiferenciadas")
  @javax.xml.ws.RequestWrapper(localName = "StartHorasDiferenciadas", targetNamespace = "http://promon.com.br/HorasDiferenciadasStart/", className = "br.com.promon.horasdiferenciadasstart.StartHorasDiferenciadas")
  @javax.jws.Oneway
  public void startHorasDiferenciadas(@javax.jws.WebParam(name = "num_mes_ref", targetNamespace = "") java.math.BigInteger num_mes_ref, @javax.jws.WebParam(name = "num_ano_ref", targetNamespace = "") java.math.BigInteger num_ano_ref);

}
