package br.com.promon.custoprofissionalstart;

/**
 * Service implementation of {CustoProfissionalStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "CustoProfissionalStart", targetNamespace = "http://promon.com.br/CustoProfissionalStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/custoprofissionalstart/CustoProfissionalStarter/CustoProfissionalStarter.wsdl")
public class CustoProfissionalStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL CUSTOPROFISSIONALSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public CustoProfissionalStart_Service() throws java.net.MalformedURLException {
    super(CUSTOPROFISSIONALSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/CustoProfissionalStart/", "CustoProfissionalStart"));
  }
  public CustoProfissionalStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [CustoProfissionalStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "CustoProfissionalStartSOAP")
  public br.com.promon.custoprofissionalstart.CustoProfissionalStart getCustoProfissionalStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/CustoProfissionalStart/","CustoProfissionalStartSOAP");
    return (br.com.promon.custoprofissionalstart.CustoProfissionalStart) super.getPort(portName,br.com.promon.custoprofissionalstart.CustoProfissionalStart.class);
  }
}
