package br.com.promon.custoprofissionalstart;

import java.util.Date;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "CustoProfissionalStart", targetNamespace = "http://promon.com.br/CustoProfissionalStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface CustoProfissionalStart {

	/**
	 * Java representation of web method [StartCustoProfissional].
	 */
	@javax.jws.WebMethod(operationName = "StartCustoProfissional", action = "http://promon.com.br/CustoProfissionalStart/StartCustoProfissional")
	@javax.xml.ws.RequestWrapper(localName = "StartCustoProfissional", targetNamespace = "http://promon.com.br/CustoProfissionalStart/", className = "br.com.promon.custoprofissionalstart.StartCustoProfissional")
	@javax.jws.Oneway
	// public void startCustoProfissional(@javax.jws.WebParam(name =
	// "dat_refer", targetNamespace = "")
	// javax.xml.datatype.XMLGregorianCalendar dat_refer);
	public void startCustoProfissional(@javax.jws.WebParam(name = "dat_refer", targetNamespace = "") Date dat_refer);

}
