package br.com.promon.retornoapontamentostart;

/**
 * Service implementation of {RetornoApontamentoStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "RetornoApontamentoStart", targetNamespace = "http://promon.com.br/RetornoApontamentoStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/retornoapontamentostart/RetornoApontamentoStarter/RetornoApontamentoStarter.wsdl")
public class RetornoApontamentoStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL RETORNOAPONTAMENTOSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public RetornoApontamentoStart_Service() throws java.net.MalformedURLException {
    super(RETORNOAPONTAMENTOSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/RetornoApontamentoStart/", "RetornoApontamentoStart"));
  }
  public RetornoApontamentoStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [RetornoApontamentoStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "RetornoApontamentoStartSOAP")
  public br.com.promon.retornoapontamentostart.RetornoApontamentoStart getRetornoApontamentoStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/RetornoApontamentoStart/","RetornoApontamentoStartSOAP");
    return (br.com.promon.retornoapontamentostart.RetornoApontamentoStart) super.getPort(portName,br.com.promon.retornoapontamentostart.RetornoApontamentoStart.class);
  }
}
