package br.com.promon.retornoapontamentostart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "RetornoApontamentoStart", targetNamespace = "http://promon.com.br/RetornoApontamentoStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface RetornoApontamentoStart {

  /**
   * Java representation of web method [StartRetornoApontamento].
   */
  @javax.jws.WebMethod(operationName = "StartRetornoApontamento", action = "http://promon.com.br/EscalasStart/StartRetornoApontamento")
  @javax.xml.ws.RequestWrapper(localName = "StartRetornoApontamento", targetNamespace = "http://promon.com.br/RetornoApontamentoStart/", className = "br.com.promon.retornoapontamentostart.StartRetornoApontamento")
  @javax.jws.Oneway
  public void startRetornoApontamento(@javax.jws.WebParam(name = "datRefer", targetNamespace = "") java.lang.String datRefer);

}
