package br.com.promon.enviaapontamentostart;

/**
 * Service implementation of {EnviaApontamentoStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "EnviaApontamentoStart", targetNamespace = "http://promon.com.br/EnviaApontamentoStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/enviaapontamentostart/EnviaApontamentoStarter/EnviaApontamentoStarter.wsdl")
public class EnviaApontamentoStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL ENVIAAPONTAMENTOSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public EnviaApontamentoStart_Service() throws java.net.MalformedURLException {
    super(ENVIAAPONTAMENTOSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/EnviaApontamentoStart/", "EnviaApontamentoStart"));
  }
  public EnviaApontamentoStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [EnviaApontamentoStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "EnviaApontamentoStartSOAP")
  public br.com.promon.enviaapontamentostart.EnviaApontamentoStart getEnviaApontamentoStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/EnviaApontamentoStart/","EnviaApontamentoStartSOAP");
    return (br.com.promon.enviaapontamentostart.EnviaApontamentoStart) super.getPort(portName,br.com.promon.enviaapontamentostart.EnviaApontamentoStart.class);
  }
}
