package br.com.promon.enviaapontamentostart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "EnviaApontamentoStart", targetNamespace = "http://promon.com.br/EnviaApontamentoStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface EnviaApontamentoStart {

  /**
   * Java representation of web method [StartEnviaApontamento].
   */
  @javax.jws.WebMethod(operationName = "StartEnviaApontamento", action = "http://promon.com.br/EscalasStart/StartEnviaApontamento")
  @javax.xml.ws.RequestWrapper(localName = "StartEnviaApontamento", targetNamespace = "http://promon.com.br/EnviaApontamentoStart/", className = "br.com.promon.enviaapontamentostart.StartEnviaApontamento")
  @javax.jws.Oneway
  public void startEnviaApontamento(@javax.jws.WebParam(name = "data_inicio", targetNamespace = "") java.lang.String data_inicio, @javax.jws.WebParam(name = "data_fim", targetNamespace = "") java.lang.String data_fim);

}
