package br.com.promon.fundacpromonfuncionariosstart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "FundacPromonFuncionariosStart", targetNamespace = "http://promon.com.br/FundacPromonFuncionariosStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface FundacPromonFuncionariosStart {

  /**
   * Java representation of web method [StartFuncionarios].
   */
  @javax.jws.WebMethod(operationName = "StartFuncionarios", action = "http://promon.com.br/FundacPromonFuncionariosStart/StartFuncionarios")
  @javax.xml.ws.RequestWrapper(localName = "StartFuncionarios", targetNamespace = "http://promon.com.br/FundacPromonFuncionariosStart/", className = "br.com.promon.fundacpromonfuncionariosstart.StartFuncionarios")
  @javax.jws.Oneway
  public void startFuncionarios(@javax.jws.WebParam(name = "par", targetNamespace = "") int par);

}
