package br.com.promon.escalasstart;

/**
 * Service implementation of {EscalasStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "EscalasStart", targetNamespace = "http://promon.com.br/EscalasStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/escalasstart/EscalasStart_EscalasStart/EscalasStart_EscalasStart.wsdl")
public class EscalasStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL ESCALASSTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public EscalasStart_Service() throws java.net.MalformedURLException {
    super(ESCALASSTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/EscalasStart/", "EscalasStart"));
  }
  public EscalasStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [EscalasStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "EscalasStartSOAP")
  public br.com.promon.escalasstart.EscalasStart getEscalasStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/EscalasStart/","EscalasStartSOAP");
    return (br.com.promon.escalasstart.EscalasStart) super.getPort(portName,br.com.promon.escalasstart.EscalasStart.class);
  }
}
