package br.com.promon.escalasstart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "EscalasStart", targetNamespace = "http://promon.com.br/EscalasStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface EscalasStart {

  /**
   * Java representation of web method [StartEscalas].
   */
  @javax.jws.WebMethod(operationName = "StartEscalas", action = "http://promon.com.br/EscalasStart/StartEscalas")
  @javax.xml.ws.RequestWrapper(localName = "StartEscalas", targetNamespace = "http://promon.com.br/EscalasStart/", className = "br.com.promon.escalasstart.StartEscalas")
  @javax.jws.Oneway
  public void startEscalas(@javax.jws.WebParam(name = "mes", targetNamespace = "") int mes, @javax.jws.WebParam(name = "ano", targetNamespace = "") int ano);

}
