package br.com.promon.pagtofolhastart;

/**
 * Service implementation of {PagtoFolhaStart} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "PagtoFolhaStart", targetNamespace = "http://promon.com.br/PagtoFolhaStart/", wsdlLocation = "META-INF/wsdl/br/com/promon/pagtofolhastart/PagtoFolhaStart/PagtoFolhaStart.wsdl")
public class PagtoFolhaStart_Service extends javax.xml.ws.Service {

  private final static java.net.URL PAGTOFOLHASTART_SERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public PagtoFolhaStart_Service() throws java.net.MalformedURLException {
    super(PAGTOFOLHASTART_SERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://promon.com.br/PagtoFolhaStart/", "PagtoFolhaStart"));
  }
  public PagtoFolhaStart_Service(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [PagtoFolhaStartSOAP].
   */
  @javax.xml.ws.WebEndpoint(name = "PagtoFolhaStartSOAP")
  public br.com.promon.pagtofolhastart.PagtoFolhaStart getPagtoFolhaStartSOAP() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://promon.com.br/PagtoFolhaStart/","PagtoFolhaStartSOAP");
    return (br.com.promon.pagtofolhastart.PagtoFolhaStart) super.getPort(portName,br.com.promon.pagtofolhastart.PagtoFolhaStart.class);
  }
}
