package br.com.promon.pagtofolhastart;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "PagtoFolhaStart", targetNamespace = "http://promon.com.br/PagtoFolhaStart/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface PagtoFolhaStart {

  /**
   * Java representation of web method [StartPagtoFolha].
   */
  @javax.jws.WebMethod(operationName = "StartPagtoFolha", action = "http://promon.com.br/EscalasStart/StartPagtoFolha")
  @javax.xml.ws.RequestWrapper(localName = "StartPagtoFolha", targetNamespace = "http://promon.com.br/PagtoFolhaStart/", className = "br.com.promon.pagtofolhastart.StartPagtoFolha")
  @javax.jws.Oneway
  public void startPagtoFolha(@javax.jws.WebParam(name = "num_mes_ref", targetNamespace = "") int num_mes_ref, @javax.jws.WebParam(name = "num_ano_ref", targetNamespace = "") int num_ano_ref);

}
